version: "3"
services:
  reservoir:
    image: reservoir:v1
    container_name: reservoir
    ports:
      - "7500:7500"
    depends_on:
      - db

  earthquake:
    image: earthquake:v1
    container_name: earthquake
    ports:
      - "8400:8400"
    depends_on:
      - db

  electricity:
    image: electricity:v1
    container_name: electricity
    ports:
      - "8551:8551"
    depends_on:
      - db


  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        mode: non-blocking

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"


  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: monitor-prometheus
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - "7070:9090"

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: monitor-grafana
  #   volumes:
  #     - ./grafana:/var/lib/grafana
  #   ports:
  #     - "3500:3000"
  #   depends_on:
  #     - prometheus

